package com.projects.stockDemo.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class HomeController {
    @GetMapping("/")
    public String home() {
        // Forward to static React app index (generated by frontend build)
        return "forward:/index.html";
    }
}
